README.md
I thought the Binder link was going to be a cool way to get started but really it takes too many steps to get going:
- As far as I can tell it's not possible to create a dot file in the home directory so you have to pass in the path to your config
- You'd have to get your server in the same config as mine to get much out of the examples
- The static previews from Github are probably just as useful
For now if someone knows how to use Binder and find it useful they can set up the link themselves.
=> Remove Binder link

.github/workflows/release.yml
Release seems to trigger three action runs:
- Created: https://github.com/getodk/pyodk/actions/runs/3131303079
- Released: https://github.com/getodk/pyodk/actions/runs/3131303075
- Published: https://github.com/getodk/pyodk/actions/runs/3131303071
This PR only runs when the release is published.
More at https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#release
=> Release triggers multiple runs, so use published

examples/2022-10-pyodk-webinar.ipynb
Thank you, @Thaliehln!
This specific one is a typo I've made more than once. For better or for worse, both do work so it's likely we'll see both pop up. I think it would be ideal for only `pyodk.client` to work so examples are consistent but I'm not sure how to achieve that.
EDIT: now I see from @Thaliehln's note that it did /not/ work. What platform are you on, @Thaliehln? I'm wondering whether the behavior I get is related to how macOS treats case for filenames. Regardless, we should be consistent in examples.
=> Fix import in notebook example

.github/workflows/verify.yml, pyodk/endpoints/forms.py, tests/test_client.py
Linters `black` and `isort` returncode is 0 when fixes required and applied, so add arguments that make it returncode 1 when fixes required. Linters `flake8 and `pycodestyle` return 1 already.
Same as https://github.com/XLSForm/pyxform/pull/631
It's the required arguments
None, only relevant for GitHub actions
No
None
=> Fix linter check for black and isort not failing when changes required

README.md, pyodk/_endpoints/auth.py, pyodk/_utils/session.py, pyodk/client.py, tests/endpoints/test_auth.py, tests/endpoints/test_comments.py, tests/endpoints/test_forms.py, tests/endpoints/test_projects.py, tests/endpoints/test_submissions.py, tests/test_client.py
Closes #21
Branched from `pyodk-6` assuming that #25 is more or less good to go.
Existing tests pass.
This makes login transparent to the user without needing a context manager, and avoids putting auth inside `client.__init__` which I think is a bit messy generally and for error handling.
No changes except where users want to adopt this new default usage style. The context manager style still works, as does `client.open()`.
No
Yes, the README is updated with the new usage example, as well as some details on login / clean up.
=> Allow building a client without resource management

examples/app_user_provisioner.py
When testing `app_user_provisioner.py`, I noticed updates were failing after scanning the QR code. This appears to because `https://` is being duplicated in `server_url`:
```
'server_url': 'https://https://...',
```
It looks like pyodk also includes `https://` in `client.auth.session.base_url`, so it can be removed from `app_user_provisioner.py`:
```
>>> from pyodk.client import Client
>>> client = Client().open()
>>> client.auth.session.base_url
'https://<snip>/v1/'
```
```
$ pip freeze | grep pyodk
pyodk==0.1.0
```
=> Remove duplicate `https://` from `server_url` in app_user_provisioner.py

.github/workflows/release.yml, .github/workflows/verify.yml
The v2 dependencies are now showing a deprecation warning, [as shown here](https://github.com/lindsay-stevens/pyodk/actions/runs/4339963389).
Successful workflow run [here](https://github.com/lindsay-stevens/pyodk/actions/runs/4341141464).
N/A
Does not affect users.
N/A
No
=> dev: update github workflow deps to latest versions

README.md, mkdocs.yml, pyodk/_endpoints/projects.py, pyodk/_endpoints/submissions.py
A few small things I noticed weren't right with the docs.
=> Misc docs fixes and improvements

pyodk/_endpoints/forms.py, tests/endpoints/test_forms.py, tests/test_client.py
Closes #34
Added unit / mocked / integration tests.
As specified in #34, except that the version passed to the version_updater func is the current form version, not the incoming draft version. In the previous issue / PR discussion (and the quoted request) it seems like it should be the current, so that the function can iterate it somehow for the new form version.
Adds a feature. Also tried to tidy up the docstring to make it clearer what is accepted by the method and how it behaves.
No
Updated docstring should be pulled into mkdocs when that's ready.
=> Add forms.update parameter to set version

.github/workflows/release.yml
Build failure at https://github.com/getodk/pyodk/actions/runs/4615333206/jobs/8159111521.
```
To https://github.com/getodk/pyodk
! [rejected]        gh-pages -> gh-pages (fetch first)
error: failed to push some refs to 'https://github.com/getodk/pyodk'
hint: Updates were rejected because the remote contains work that you do
hint: not have locally. This is usually caused by another repository pushing
hint: to the same ref. You may want to first integrate the remote changes
hint: (e.g., 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.
```
Found solution at https://squidfunk.github.io/mkdocs-material/publishing-your-site
=> Force the push to the docs branch

README.md, docs/http-methods.md
Closes #51
Looked at docs site to see what link should be and updated the files accordingly.
Correct links
Better docs navigation
N/A
Docs update
=> fix: docs links

README.md, docs/examples/README.md, docs/http-methods.md, pyodk/_endpoints/auth.py
One thing I noticed that we only publish docs on release, so after this is merged, I will need to run `mkdocs gh-deploy --force` locally...
=> Fix API docs links and internal links

docs/examples/2022-10-pyodk-webinar.ipynb, docs/examples/beyond-library-methods.ipynb
=> Update links from Apiary to docs site

README.md, docs/entities.md, docs/entity_lists.md, mkdocs.yml, pyodk/_endpoints/entities.py, pyodk/_endpoints/entity_lists.py, pyodk/_endpoints/projects.py, pyodk/_utils/validators.py, pyodk/client.py, tests/endpoints/test_entities.py, tests/endpoints/test_entity_lists.py, tests/resources/entities_data.py, tests/resources/entity_lists_data.py, tests/test_client.py, tests/utils/entity_lists.py
Closes #62
Adds methods:
- client.entity_lists.list
- client.entities.list
- client.entities.create
- client.entities.get_table
Other entity_lists methods in #62 not included as they aren't publicly documented yet, so I don't know what the proper call pattern or response type/schema is. Although I took a guess based on manual testing for the test setup function in `tests/utils/entity_lists.py`.
E2E tests added to `test_client.py` as well as usual unit tests.
I split entities from entity_lists, because they are separate object types. Due to the similar names it was confusing for me initially to tell the difference between an entity and entity_list and what they are supposed to do. Especially considering `entity.list()`, `entity_list.list()`. So the docstrings for EntityService and …
=> 62: add support for entities and entity_lists

README.md, docs/examples/app_user_provisioner/requirements.txt
The intent for the app user provisioner example is for it to be a standalone script. I considered briefly whether it would make sense to introduce a pyproject.toml file for it but from https://stackoverflow.com/a/76548420/137744 decided requirements.txt was the most appropriate for pinned dependencies.
That led me to wonder a bit about the top-level pyproject.toml file and whether it should include pinned versions or not. I don't think it's a big deal because we don't know of anyone packaging pyodk as part of a larger system but we may want to eventually separate declared dependencies and pinned versions.
I also noticed that the readme mentions python 3.8 which it should not. @lindsay-stevens do you use `pyenv`? Happy to recommend something else if you prefer (but I do 💜 `pyenv`!).
=> Update example dependencies, recommend pyenv

pyodk/_endpoints/entities.py, pyodk/_endpoints/form_draft_attachments.py, pyodk/_endpoints/form_drafts.py, pyodk/_endpoints/forms.py, pyodk/_utils/session.py, pyodk/_utils/validators.py, pyproject.toml, tests/endpoints/test_forms.py, tests/resources/forms/range_draft.xml, tests/resources/forms_data.py, tests/test_client.py, tests/utils/forms.py, tests/utils/md_table.py
Closes #60
Adds method `client.forms.create`. There is a parameter for ignore_warnings which defaults to False. The publish parameter is hard coded to True as per #60. The form ID logic is slightly different, as follows - since pyODK has a form_id param and potentially a file path it seemed sensible to prioritise those before a uuid-based form ID fallback.
form_id defaults behaviour for create/update:
- was:
- form_id in the file (assuming Central reads and prioritises that)
- definition file_path.stem
- now:
- form_id in the file (assuming Central reads and prioritises that)
- form_id (or default) provided to pyodk
- definition file_path.stem
- random UUID
Also since I anticipated this being used in pyxform-http or similar I made create/update accept bytes. So you could read in the …
=> 60: add form creation

README.md
Closes #10
This mostly inserts the notes from the issue. It feels like they've stood up well through the functionality we've added recently!
I feel like this matches what we've been considering as part of API design but it's only good if @lindsay-stevens agrees!
None.
No.
It is!
=> Add design considerations

README.md
A couple of quick additions to consider following #80. I wanted to play a little bit with the wording to try to guide users towards noticing their Central server is out of date. I think 404s will be the most common errors.
We could also add those details to a wrapper for 404 errors but I think we can hold off until we get some reports of the issue.
While there, I also tried to soften/contextualize the `pyenv` recommendation.
@lindsay-stevens feel free to push directly to the branch if you want to try iterating on it a bit!
=> Add minor details about Central version

README.md, pyodk/_endpoints/entities.py, tests/endpoints/test_entities.py, tests/resources/entities_data.py, tests/test_client.py
Closes #73
New unit and integration tests.
Added function is as specified in #73. One minor assumption: an error is raised if both `force` and `base_version` are provided. It seemed like that might be dangerous as well, e.g. user specifies the wrong base_version but gets an update anyway.
New convenience method.
N/A
No
=> 73: add client.entities.update

.github/workflows/release.yml
Docs publishing doesn't work because dependency installation isn't expressed quite right.
=> Fix docs dep install

pyodk/_endpoints/forms.py, tests/resources/forms_data.py
Closes #90
Updated test fixture data to include a form where these fields are null, and ran the test suite.
I think I had made `name` and `enketoId` required since every request I made during testing had those fields.
I read the current [Central code](https://github.com/getodk/central-backend/blob/0cd56948854ecc544a1b4af9efd88cf9ceee153d/lib/model/frames/form.js) that seems to return this data. Per Line 79: nullable `enketoId`, and Line 117: nullable `name`. From what I can tell, Line 50 is saying that both fields are always part of the returned object, whether null or not. According to the forum thread linked in #90, and the Central docs, it's possible to use Central without Enketo and in that case `enketoId` may be blank. I assumed everyone used them together but apparently not. About …
=> 90: make enketoId and name optional in the Form model

pyodk/_endpoints/forms.py, tests/endpoints/test_forms.py, tests/test_client.py
Closes #79
New tests, checked E2E result in Central
Follows a similar pattern to forms.update but without the version update, and a definition is required. The attachment upload and publish are separate calls because the form creation endpoint in Central accepts only a form definition.
The returned Form object doesn't include info about the attachments, because if an upload fails then an error will be raised (before the form is published), so a user could assume that no error means all attachments were uploaded.
New convenience feature to avoid needing to create then update just to upload attachments.
No
The method docstring is updated with the new parameter.
=> add: form creation with attachments

docs/examples/create_entities_from_submissions/create_entities_from_submissions.py, pyodk/_endpoints/entities.py, pyodk/_endpoints/entity_lists.py, pyodk/_utils/validators.py, pyproject.toml, tests/endpoints/test_entities.py, tests/test_client.py
Closes #88
Unit tests for the data processor method `_prep_data_for_merge`, and integration tests in `test_client.py`.
The original ticket called for an example script but 1) this seemed like functionality that would be widely useful enough to be a part of the library itself, and 2) it was somewhat complicated to implement and test (lots of options and edge cases) so as part of the library it should be easier to actively maintain.
Also, I added the use case to the existing example script `create_entities_from_submissions.py` because there was an almost complete overlap in the use case - it didn't involve updating data before, but you can do the same thing with `merge`. The tests contain examples of numerous other usage / call patterns.
Provides some handy new ways to interact with …
=> 88: add entities methods create_many, delete, merge

.github/workflows/verify.yml, docs/examples/2022-10-pyodk-webinar.ipynb, docs/examples/basic-analysis-pandas.ipynb, docs/examples/beyond-library-methods.ipynb, docs/examples/working-with-repeats.ipynb, pyodk/_endpoints/auth.py, pyodk/_utils/session.py, pyproject.toml
- pydantic dependency assumes latest version in the range.
- added actions job tests with the lower bound as well.
- probably most likely package to cause conflicts for users e.g. #94
- requests not tested this way because often its releases are for security patches.
- e.g. 2.32.0 and 2.32.1 were yanked for security reasons
- includes formatting changes via ruff update
Ran tests locally and GitHub actions CI
As mentioned above
Updates dependencies to latest versions
No
=> update dependencies, add job to test older pydantic

.github/workflows/verify.yml, README.md, pyproject.toml, tests/resources/forms_data.py, tests/utils/entity_lists.py
Closes #106
Updated CI jobs to test on all versions.
The ticket says up to 3.12, but 3.13 has been out for about 18 months and there as a [forum post](https://forum.getodk.org/t/50108) about it in Oct 2024. According to pypi, requests supports python 3.8-12, toml 3.3-9, pydantic 3.8-13.
Should enable more use cases without affecting existing python 3.12 use. There were some minor code / formatting changes but these should not affect users.
N/A
Updated Readme doc with the new versions. As noted there the primary dev version is still 3.12 for now, and I updated the quoted Central version since that's the version on staging and the E2E tests in `test_client.py` pass against it.
=> 106: Support Python 3.10 - 3.13

.github/workflows/release.yml, .github/workflows/verify.yml, pyproject.toml
Fixes CI docs build job failure at `mkdocs build --strict` step, which blocks the automated tests job in GitHub actions file `verify.yml` ([example Actions run](https://github.com/getodk/pyodk/actions/runs/13757052515)). Probably would block publishing in `release.yml` as well.
- CI docs build job passed
- local docs build passed
- checked each page in local docs build vs. current published version
- pages look the same and nothing obviously weird looking (desktop view size, Firefox v136).
Initially I just kicked the can down the road by adding a dependency for `mkdocs-autorefs`. But I thought I'd see if the most recent docs deps versions were compatible with Python 3.12 and each other, and it seems they are. If it had required changing configs (`mkdocs.yml`) or content changes …
=> Docs CI fix

pyodk/_endpoints/bases.py, pyodk/_endpoints/comments.py, pyodk/_endpoints/entities.py, pyodk/_endpoints/entity_list_properties.py, pyodk/_endpoints/entity_lists.py, pyodk/_endpoints/form_assignments.py, pyodk/_endpoints/form_draft_attachments.py, pyodk/_endpoints/form_drafts.py, pyodk/_endpoints/forms.py, pyodk/_endpoints/project_app_users.py, pyodk/_endpoints/projects.py, pyodk/_endpoints/submissions.py
Closes #103
- update bases.Model config to equivalent pydantic v3 style
- URLs classes are meant to be mostly immutable reference objects, so swap to smaller dataclass alternative rather than updating the pydantic usage
- shorten imports from bases module
Ran unit and integration tests. Checked warning behaviour by launching python:
- prior to commit, default warnings, no warning: `python -c "from pyodk import Client"`
- prior to commit, warnings forced on, warning shown: `python -Wdefault -c "from pyodk import Client"`
- post commit, warnings forced on, no warning shown: `python -Wdefault -c "from pyodk import Client"`
The warning in question:
```
/home/u/repos/pyodk/venv/lib/python3.12/site-packages/pydantic/_internal/_config.py:291: PydanticDeprecatedSince20: Support for class-based …
```
=> 103: avoid pydantic v3 DeprecationWarning when warnings are enabled

pyodk/_endpoints/submission_attachments.py, pyodk/_endpoints/submissions.py, pyodk/_utils/session.py, tests/endpoints/test_submissions.py, tests/resources/forms_data.py, tests/resources/submissions_data.py, tests/test_client.py, tests/utils/entity_lists.py
Closes #102
- accepts a list of paths and sends in chunks to account for large files
- adds setting on session object for blocksize, although it is the same as default it allows customisation for advanced users
- fix: entity_list test fixture creation flow, noticed when running tests against a new Central instance (dev)
Added unit and integration tests, plus some manual testing to check behaviour mentioned below.
In reference to #102 the code could now look like:
```python
#!/usr/bin/env python3
from pathlib import Path
from pyodk.client import Client
client = Client()
for folder in Path("/Users/me/Desktop/instances").iterdir():
if folder.is_dir():
client.submissions.create(
project_id=1,
form_id="my_form",
xml=(folder / "instance.xml").read_text(),
attachments=(f for f in …
```
=> 102: submission attachment upload with submission.create

pyodk/_endpoints/form_draft_attachments.py, pyodk/_endpoints/forms.py, tests/endpoints/test_forms.py, tests/resources/forms_data.py, tests/test_client.py
Closes #115
- the form attachment upload endpoint now returns a json object representing attributes of the file, rather than a generic status message `{"success": True}`
- set a content-type header for form attachments, in the same way as for submission attachments, since both seem to require it when Central uses S3 file storage
- it seems webforms errors out if no content-type is set, but enketo is OK
- also in test_client.py change the print() calls to basic non-none assertions since staging now has quite a lot of data which means those print calls are very noisy.
Added unit test to check the content-type change, ran integration tests to check generally. Opened forms created before the change (enketo OK, webforms errored) and after the change (enketo OK, webforms different probably …
=> 115: form attachments update for Central v2025.1, set content-type
